# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='teams',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
