# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_signup_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='teams',
            new_name='package',
        ),
    ]
