# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_signup_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Profile',
        ),
    ]
