# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20180116_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
