# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_auto_20180424_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
